language: python
dist: xenial

python:
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install -e .
  - pip install --upgrade -r requirements-dev.txt

script:
  - py.test
  - pylint -E russell

sudo: false
