language: python

python:
  - '3.3'
  - '3.4'
  - '3.5'

install:
  - pip install -e .
  - pip install -r requirements_dev.txt

script:
  - py.test --cov russell
  - pylint -f text russell

sudo: false
