language: python
dist: xenial

python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install -e .
  - pip install --upgrade -r requirements-dev.txt

script:
  - black --check russell
  - pylint -E russell
  - pytest

sudo: false
