language: python

python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install -e .
  - pip install -r requirements-dev.txt

script:
  - py.test --runslow
  - pylint -E russell

sudo: false
