branches:
  - master

dist: xenial
sudo: false
language: python
cache:
  pip: true

python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
install: pip install -e . --upgrade pytest
script: pytest

jobs:
  include:
    - name: black
      install: pip install --upgrade black
      script: black --check .

    - name: pylint
      install: pip install -e . --upgrade pylint
      script: pylint -E russell
